[package]
name = "abw"
version = "0.1.0"
edition = "2024"
authors = ["Marco Ferragina <marco.ferragina@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/ferama/abw"
license = "MIT"

[dependencies]

[package.metadata.wix]

[profile.release]
codegen-units = 1
lto = true
strip = true
