name: Release

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'
    branches:
      - '**'

jobs:
  build:
    name: Build release binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            arch_name: x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      
      - name: Install cargo-wix
        run: |
          cargo install --version 0.3.9 cargo-wix
        shell: powershell
      
      - name: Run build.ps1
        run: |
          powershell .\scripts\build.ps1
        shell: powershell

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Build MSI Installer
        run: >
          cargo wix -v --no-build --nocapture
          --target ${{ matrix.target }} 
          --output target/${{ matrix.target }}/release/abw-${{ matrix.arch_name }}.msi
      
      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: abw-${{ matrix.arch_name }}
          path: |
            target/${{ matrix.target }}/release/abw-${{ matrix.arch_name }}.msi
      

  release:
    name: Upload Release Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Checksums
        run: |
          for file in artifacts/abw-*/abw-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done
          find artifacts
      
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: artifacts/**/*
          token: ${{ secrets.GITHUB_TOKEN }}